resources:
  - name: tic-tac-toe
    type: git
    source: 
      uri: https://github.com/andrewrisse/tic-tac-toe
      branch: develop
  - name: resource-gist
    type: git
    source:
      branch: master
      uri: 
      private_key: |-

jobs:
  - name: job-build-tic-tac-toe-app
    serial: true
    plan:
      - get: tic-tac-toe
      - get: resource-gist
      - task: ticTacBuildScript
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: starkandwayne/concourse}

          inputs:
            - name: tic-tac-toe
            - name: resource-gist
          outputs:
            - name: updated-gist
          run:
            path: tic-tac-toe/ticTacBuildScript.sh

      - put: resource-gist
        params:
          repository: updated-gist
