---
resources:
  - name: tic-tac-toe
    type: git
    source:
      uri: https://github.com/andrewrisse/tic-tac-toe
      branch: master

jobs:
  - name: tic-tac-toe-build
    public: true
    plan:
      - get: tic-tac-toe
      - task: ticTacBuildScript
        file: ./tic-tac-toe.yml
