---
resources:
  - name: tic-tac-toe
    type: git
    source:
      uri: https://github.com/andrewrisse/tic-tac-toe
      branch: master

jobs:
  - name: job-build-tic-tac-toe
    serial: true
    plan:
      - get: tic-tac-toe
      - task: build-tic-tac-toe
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: starkandwayne/concourse}
          inputs:
            - name: tic-tac-toe
          run:
            path: ./ticTacBuildScript.sh
 