---
resources:
  - name: tic-tac-toe
    type: git
    source:
      uri: https://github.com/andrewrisse/tic-tac-toe
      branch: dev

jobs:
  - name: job-build-tic-tac-toe
    serial: true
    plan:
      - get: tic-tac-toe
        trigger: true
      - task: build-tic-tac-toe
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node}
          inputs:
            - name: tic-tac-toe
          run:
            path: tic-tac-toe/ticTacBuildScript.sh
 