---
resources:
  - name: tic-tac-toe
    type: git
    source:
      uri: https://github.com/andrewrisse/tic-tac-toe
      branch: master
  

jobs:
  - name: job-build-tic-tac-toe
    serial: true
    plan:
      - get: tic-tac-toe
      - get: resource-gist
      - task: build-tic-tac-toe
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: starkandwayne/concourse}
          inputs:
            - name: tic-tac-toe
            - name: resource-gist
          outputs:
            - name: updated-gist
          run:
            path: ./ticTacBuildScript.sh
      - put: resource-gist
        params: {repository: updated-gist}